[general]
live_config_reload = true

import = ["~/.config/alacritty/catppuccin-frappe.toml"]

# [[colors.indexed_colors]]
# color = "#ff9e64"
# index = 16

# [[colors.indexed_colors]]
# color = "#db4b4b"
# index = 17

# [colors.bright]
# black = "#414868"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#9ece6a"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#c0caf5"
# yellow = "#e0af68"

# [colors.normal]
# black = "#15161e"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#9ece6a"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#a9b1d6"
# yellow = "#e0af68"

# [colors.primary]
# background = "#1a1b26"
# foreground = "#c0caf5"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001b1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[window]
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = false

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"
